[package]
name = "sher_device_manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sher_common = { path = "../common" }
sher_objectmodel = { path = "../objectmodel" }
sher_security = { path = "../security" }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
