[package]
name = "sher_services"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Optional services: filesystem, networking, storage, display, audio"

[dependencies]
sher_common = { path = "../common" }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
